### ISSUE TITLE
many error when Installing dependencies

### ISSUE THREAD

**Issue by TWO-ONE-21** [Technowlogy-Pushpender/technowhorse#3]
when I installing dependencies. I get many error. it's the error:
```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-AtOJB_/essential-generators/setup.py", line 8, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-AtOJB_/essential-generators/
```

```
Collecting pywin32
  Could not find a version that satisfies the requirement pywin32 (from versions: )
No matching distribution found for pywin32
```

please help me:)

**Comment by PushpenderIndia** [comment]
Try to download New "installer_linux.sh" and run it again.

If the problem still persist, then try to run each command present in installer_linux.sh manually
